name: 'demo_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'dbt_demo'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "logs"

models:
  +persist_docs:
    relation: true
    columns: true
  demo_dbt_project:
      base:
          materialized: table
      applicant:
          materialized: table