version: 2

dbt_demo:
    target: dev
    outputs:
        dev:
          type: bigquery
          method: oauth
          project: pe2024 
          dataset: customer_reporting_zone
          location:  us-central1
